@startuml
skinparam shadowing false
skinparam monochrome true
skinparam roundcorner 12
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 17
skinparam ArrowFontSize 13
skinparam ArrowThickness 2
skinparam linetype ortho
skinparam dpi 600

skinparam activity {
BorderColor black
BackgroundColor white
}

<style>
activityDiagram {
activity {
HorizontalAlignment center
}

diamond {
HorizontalAlignment center
}
}
</style>

skinparam diamond {
BorderColor black
BackgroundColor white
}

start

repeat

:Получить технически\nкорректный вариант;
:VLM оценка;

if ( ) then (диаграмма прошла\nпроверку)

:Принять текущий\nвариант;

else (диаграмма не прошла\nпроверку)

if ( ) then (лимит семантических\nповторов исчерпан)
:Выбрать лучший\nполученный вариант;
else (лимит семантических\nповторов не исчерпан)
:Семантический повтор:\nучесть замечания VLM;
:Повторная генерация\nи техническая проверка;
endif

endif

repeat while ( ) is (нужен семантический\n повтор) not (вариант выбран)

:Итоговый\nVLM-анализ;

stop

@enduml