@startuml
skinparam shadowing false
skinparam monochrome true
skinparam roundcorner 12
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 17
skinparam ArrowFontSize 13
skinparam ArrowThickness 2
skinparam linetype ortho
skinparam dpi 600

skinparam activity {
BorderColor black
BackgroundColor white
}

<style>
activityDiagram {
activity {
HorizontalAlignment center
}

diamond {
HorizontalAlignment center
}
}
</style>


skinparam diamond {
BorderColor black
BackgroundColor white
}

start

repeat
:Получение знаний из VisRAG;
:Генерация\nVega-Lite спецификации;
: Проверка\nспецификации;

if ( ) then (спецификация\n валидна)

: Рендер диаграммы\nи получение графа сцены;
:Проверка построения\nи непустоты;

if ( ) then (диаграмма построена\nи не пуста)

:Техническая проверка\n пройдена;

else (диаграмма не построена\nили пуста)

if ( ) then ( лимит технических\nповторов исчерпан)
:Техническая ошибка\n построения;
stop
else (лимит технических\nповторов не исчерпан)
: Технический повтор:\nисправить спецификацию;
endif

endif

else (спецификация\nневалидна)

if ( ) then ( лимит технических\nповторов исчерпан)
: Ошибка\nгенерации;
stop
else (лимит технических\nповторов не исчерпан)
: Технический повтор:\nисправить спецификацию;
endif

endif

repeat while ( ) is (нужен технический  nповтор) not (техническая проверка\n пройдена)

:Передать построенный\nвариант в семантический цикл;

stop

@enduml