@startuml
title VegaChat / EDAPlot - архитектура из статьи и кода

hide empty description

[*] --> DatasetLoaded
DatasetLoaded --> HeaderAnalyzer
DatasetLoaded --> ChartRecommender

[*] --> Query
Query --> RequestAnalyzer

HeaderAnalyzer --> RequestAnalyzer
ChartRecommender --> RequestAnalyzer

RequestAnalyzer --> ChartGenerator
ChartGenerator --> VegaLiteSpec

VegaLiteSpec --> SpecValidator
SpecValidator --> ScenegraphCheck
ScenegraphCheck --> EmptyChartCheck

SpecValidator --> ChartGenerator : invalid spec / fix
EmptyChartCheck --> ChartGenerator : empty chart / fix

EmptyChartCheck --> Renderer
Renderer --> Visualization

VegaLiteSpec --> SpecScore
Visualization --> VisionScore

SpecScore --> EvaluationSummary
VisionScore --> EvaluationSummary

EvaluationSummary --> [*]



@enduml