project_dir: .
corpus_path: rag_corpus/autorag/vega_lite/corpus.parquet
qa_path: rag_corpus/autorag/vega_lite/qa_mixed_technical.parquet

vectordb:
  - name: chroma_hf_bge_small_en_v15
    db_type: chroma
    client_type: persistent
    embedding_batch: 16
    embedding_model:
      - type: huggingface
        model_name: BAAI/bge-small-en-v1.5
    collection_name: vega_lite_bge_small_en_v15
    path: rag_corpus/autorag/vega_lite/chroma/bge_small_en_v15

node_lines:
  - node_line_name: retrieve_bm25_main
    nodes:
      - node_type: lexical_retrieval
        strategy:
          metrics:
            - retrieval_f1
            - retrieval_recall
            - retrieval_precision
            - retrieval_ndcg
            - retrieval_mrr
          speed_threshold: 10
        top_k: 5
        modules:
          - module_type: bm25
            bm25_tokenizer: porter_stemmer

  - node_line_name: retrieve_semantic_bge_main
    nodes:
      - node_type: semantic_retrieval
        strategy:
          metrics:
            - retrieval_f1
            - retrieval_recall
            - retrieval_precision
            - retrieval_ndcg
            - retrieval_mrr
          speed_threshold: 10
        top_k: 5
        modules:
          - module_type: vectordb
            vectordb: chroma_hf_bge_small_en_v15

  - node_line_name: retrieve_hybrid_rrf_main
    nodes:
      - node_type: lexical_retrieval
        strategy:
          metrics:
            - retrieval_f1
            - retrieval_recall
            - retrieval_precision
            - retrieval_ndcg
            - retrieval_mrr
          speed_threshold: 10
        top_k: 5
        modules:
          - module_type: bm25
            bm25_tokenizer: porter_stemmer

      - node_type: semantic_retrieval
        strategy:
          metrics:
            - retrieval_f1
            - retrieval_recall
            - retrieval_precision
            - retrieval_ndcg
            - retrieval_mrr
          speed_threshold: 10
        top_k: 5
        modules:
          - module_type: vectordb
            vectordb: chroma_hf_bge_small_en_v15

      - node_type: hybrid_retrieval
        strategy:
          metrics:
            - retrieval_f1
            - retrieval_recall
            - retrieval_precision
            - retrieval_ndcg
            - retrieval_mrr
          speed_threshold: 10
        top_k: 5
        modules:
          - module_type: hybrid_rrf
            weight_range: "(10, 80)"
