@startuml
title Планирование подзадач в ViRAGE

skinparam shadowing false
skinparam monochrome true
skinparam roundcorner 12
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 18
skinparam ArrowFontSize 16
skinparam ArrowThickness 2
skinparam linetype ortho
skinparam dpi 600

skinparam activity {
BorderColor black
BackgroundColor white
}

<style>
activityDiagram {
activity {
HorizontalAlignment center
}

diamond {
HorizontalAlignment center
}
}
</style>

start

:Получить пользовательский запрос\nи таблицу данных;
:Построить профиль данных;
:Определить доступные поля,\nтипы данных и ограничения таблицы;

if () then (Запрос содержит\nнесколько целей)
:Разделить запрос\nна подзадачи;
else (Запрос содержит\nодну цель)
:Создать одну \nподзадачу;
endif

:Ограничить число подзадач\nдо установленного предела;
:Назначить каждой подзадаче\nцель анализа;
:Выбрать поля таблицы;
:Получить рекомендации VisRAG;
:Сформировать план выполнения;

repeat
:Выполнить очередную подзадачу;
:Сохранить спецификацию,\nграфик и текстовый анализ;
repeat while () is (Остались\nневыполненные\nподзадачи) not ( Все задачи\n выполнены)

:Агрегировать результаты;
:Сформировать итоговый вывод;

stop

@enduml