@startuml
skinparam shadowing false
skinparam monochrome true
skinparam roundcorner 12
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 18
skinparam ArrowFontSize 16
skinparam ArrowThickness 2
skinparam linetype ortho
skinparam dpi 600

skinparam activity {
  BorderColor black
  BackgroundColor white
}

skinparam diamond {
  BorderColor black
  BackgroundColor white
}

<style>
activityDiagram {
  activity {
    HorizontalAlignment center
  }

  diamond {
    HorizontalAlignment center
  }
}
</style>

start

:Получить пользовательский запрос
и входные данные;
:Построить профиль данных;
:Определить доступные поля,
типы данных и ограничения;
:Выделить аналитические задачи;

if () then (В запросе несколько подзадач)
  :Разделить запрос не более чем
на три аналитические задачи;
else (В запросе одна подзадача)
  :Сформировать одну
аналитическую задачу;
endif

:Назначить каждой задаче цель,
поля и требуемые преобразования;
stop
@enduml
